CREATE TABLE TURMA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME VARCHAR(100) NOT NULL
);

CREATE TABLE ALUNO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(100) NOT NULL,
  NOME_RESPONSAVEL VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(11) NOT NULL,
  TELEFONE_RESPONSAVEL VARCHAR(11) NOT NULL,
  ID_TURMA INTEGER,
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID)
);